[options]
admin_passwd = admin

db_host = localhost
db_port = 5432
db_name = odoodata
db_user = odoouser
db_password = odoo123
addons_path = odoo/addons,myaddons,base_accounting_kit,muk_theme_addon
http_port = 8069

# logfile = C:\odoo19\odoo.log
# App Password: mmgo dwvi bpdy obou
